export const funnyTabTitles = [
  {
    title: "How to fix CSS that's already perfect",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Is flexbox gaslighting me?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "StackOverflow - 57 tabs open",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Buy 1px ruler for CSS precision",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Top 10 excuses for missed deadlines",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "HTML: Why won't you listen to me?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Dog wearing sunglasses - MUST SEE",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Should I learn Rust? (again)",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "404 - My brain not found",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Emergency Pizza Recipes",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "How many tabs is too many tabs?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "React Error: Probably Your Fault™",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Best chairs for coding 48 hours straight",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "How to turn coffee into code",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Ultimate Guide to Closing Tabs (Fail)",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Secret Life of a CSS Wizard",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "CSS Variables - Are They Alive?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "The Great Debate: Tabs vs Spaces",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Help! I lost my div",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Procrastination tips for productive people",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Learning Kubernetes in 10 minutes (impossible)",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Napping vs Debugging",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "CSS Grid: Black Magic Explained",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Did I save before refreshing?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Screaming Internally: A Developer's Tale",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "You opened this tab. Now you must suffer.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Click me if you dare.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "One does not simply close a tab.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Congrats! You found the useless tab.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "This tab is judging you.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Infinite loop detected. Send help.",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "How to explain bugs without crying",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Best ways to pretend you're working",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Can I eat JavaScript? Asking for a friend",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "StackOverflow down?! PANIC!",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Latest trends in procrastination",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Ctrl + Z: My real superpower",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "404: Motivation not found",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Why is this button slightly off center?",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Breaking News: Developer touches grass",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "I swear it worked yesterday",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Compiling… compiling… compiling…",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Error: Brain.exe has crashed",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Google: How to Google better",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Building a spaceship with CSS (WIP)",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Dreaming of semicolons",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Debugger: It's always YOUR fault",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Keyboard smashed itself out of rage",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
  {
    title: "Life is short, write bad code fast",
    isClosed: false,
    isAtBottom: false,
    xPosition: 0,
  },
];
