export const funnyTabTitles = [
  "How to fix CSS that's already perfect",
  "Is flexbox gaslighting me?",
  "StackOverflow - 57 tabs open",
  "Buy 1px ruler for CSS precision",
  "Top 10 excuses for missed deadlines",
  "HTML: Why won't you listen to me?",
  "Dog wearing sunglasses - MUST SEE",
  "Should I learn Rust? (again)",
  "404 - My brain not found",
  "Emergency Pizza Recipes",
  "How many tabs is too many tabs?",
  "React Error: Probably Your Fault™",
  "Best chairs for coding 48 hours straight",
  "How to turn coffee into code",
  "Ultimate Guide to Closing Tabs (Fail)",
  "Secret Life of a CSS Wizard",
  "CSS Variables - Are They Alive?",
  "The Great Debate: Tabs vs Spaces",
  "Help! I lost my div",
  "Procrastination tips for productive people",
  "Learning Kubernetes in 10 minutes (impossible)",
  "Napping vs Debugging",
  "CSS Grid: Black Magic Explained",
  "Did I save before refreshing?",
  "Screaming Internally: A Developer's Tale",
  "You opened this tab. Now you must suffer.",
  "Click me if you dare.",
  "One does not simply close a tab.",
  "Congrats! You found the useless tab.",
  "This tab is judging you.",
  // 🎉 New funny ones below
  "Infinite loop detected. Send help.",
  "How to explain bugs without crying",
  "Best ways to pretend you're working",
  "Can I eat JavaScript? Asking for a friend",
  "StackOverflow down?! PANIC!",
  "Latest trends in procrastination",
  "Ctrl + Z: My real superpower",
  "404: Motivation not found",
  "Why is this button slightly off center?",
  "Breaking News: Developer touches grass",
  "I swear it worked yesterday",
  "Compiling… compiling… compiling…",
  "Error: Brain.exe has crashed",
  "Google: How to Google better",
  "Building a spaceship with CSS (WIP)",
  "Dreaming of semicolons",
  "Debugger: It's always YOUR fault",
  "Keyboard smashed itself out of rage",
  "Life is short, write bad code fast",
];
