import "../styles/globals.css";

export const metadata = {
  title: "Abdelrahman Mostafa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-quicksand`}>{children}</body>
    </html>
  );
}
